backend:
  name: github
  repo: silifkedalismerkezi/silifke-dalis-merkezi   # <- repo adını kendi GitHub'ına göre değiştir
  branch: main
media_folder: "public/images/gallery"
public_folder: "/images/gallery"
collections:
  - name: "site"
    label: "Site Ayarları"
    files:
      - file: "public/site.json"
        label: "Genel Bilgiler"
        name: "settings"
        fields:
          - {label: Telefon, name: phone, widget: string}
          - {label: E-posta, name: email, widget: string}
          - {label: Adres, name: address, widget: string}
          - label: Sosyal Medya
            name: social
            widget: object
            fields:
              - {label: Instagram, name: instagram, widget: string, required: false}
              - {label: Facebook, name: facebook, widget: string, required: false}
              - {label: YouTube, name: youtube, widget: string, required: false}
          - label: Galeri
            name: gallery
            widget: list
            field: {label: Görsel, name: src, widget: image}
